### ISSUE TITLE
Quest Line

### ISSUE THREAD

**Issue by JenTheWren** [EvergoodTeam/Evergood#1]
The first quest that I see "Punch some trees" requires another quest called "Let's begin." I cannot find this quest anywhere. 

Can you help?

Thanks,

Jen the Wren

**Comment by Librv** [comment]
Hello! The first quest was locked off because quests aren't done at all. 80% of them are only icons with no quest name and/or task. It'll be available once quests are at a somewhat playable stage.

If you really want to play them, you can run the command "/bq_admin edit" and either remove the requirements or the task itself or just auto-complete it with the designer tools.
Have a great day
